# Generated by Django 4.2.5 on 2024-01-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
